<h1>Se ha producido un error</h1>
<h2><?php echo $this->exception->getMessage() ?></h2>
<h3>Stack trace</h3>
<pre><?php print_r($this->exception->getTraceAsString()) ?></pre>
<?php if($this->exception->getPrevious()){ ?>
	<h4>Previous Exceptions</h4>
	<?php $e = $this->exception;
	while ($e = $e->getPrevious()){ ?>
		<h5><?php echo $e->getMessage() ?></h5>
		<pre><?php print_r($e->getTraceAsString()); ?></pre>
	<?php }
} ?>